tissues:
        mmu: 
                liver: [SRS387309] # insert relevant sample accessions here
        hsa:
samples:
         SRS387309: [SRR652248]

single_end: [SRR652248]
paired_end: []

mouse:
        runs: [SRR652248]

human:
        runs: []

mirnas: [mmu-miR-29b-3p,mmu-miR-132-3p, mmu-miR-7061-5p] #if this configuration is left blank - processing is performed for all miRNAs of a given species as default
transcripts: [ENSMUST00000055032.13] #if this configuration is left blank - processing is performed for all transcripts of a given species by default
